TRAIN:
  ENABLE: False
  DATASET: EpicSounds
  BATCH_SIZE: 128
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 1
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_EPOCH_RESET: True
  AUTO_RESUME: True
AUDIO_DATA:
  CLIP_SECS: 1.999 # 0.999 1.999
  NUM_FRAMES: 400 # 200  400
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  FREEZE: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.001
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 25]
  LRS: [1, 0.1]
  MAX_EPOCH: 30
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: -1.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: [44]
  ARCH: slowfast
  MODEL_NAME: SlowFastAudio
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.0 # 0.5
TEST:
  ENABLE: True
  DATASET: EpicSounds
  BATCH_SIZE: 1 # 128
  NUM_ENSEMBLE_VIEWS: 1 # 5 num_clips, 就是一段长音频可能ove的抽取多少段
  CHECKPOINT_FILE_PATH: /mnt/fast/nobackup/scratch4weeks/pz00220/code/Long-Form-Audio-Understanding/src/slowfast/checkpoint/SLOWFAST_EPIC_SOUNDS.pyth
DATA_LOADER:
  NUM_WORKERS: 0
  PIN_MEMORY: True
WANDB:
  ENABLE: False
NUM_GPUS: 0 # 8
NUM_SHARDS: 1
RNG_SEED: 0

